#include "mruby.h"
#include "mruby/string.h"
#include "iup.h"

#define MRB_IUP_CONST(n) mrb_define_const(mrb, iup, #n, mrb_fixnum_value(IUP_##n));

#define MRB_IUP_STR(n) mrb_define_const(mrb, iup, #n, mrb_str_new_cstr_frozen(mrb, IUP_##n));

void
mrb_init_iup_constants(mrb_state *mrb, struct RClass *iup)
{
  MRB_IUP_CONST(ERROR);
  MRB_IUP_CONST(NOERROR);
  MRB_IUP_CONST(OPENED);
  MRB_IUP_CONST(INVALID);
  MRB_IUP_CONST(INVALID_ID);

  MRB_IUP_CONST(IGNORE);
  MRB_IUP_CONST(DEFAULT);
  MRB_IUP_CONST(CLOSE);
  MRB_IUP_CONST(CONTINUE);

  MRB_IUP_CONST(LEFT);
  MRB_IUP_CONST(CENTER);
  MRB_IUP_CONST(RIGHT);
  MRB_IUP_CONST(MOUSEPOS);
  MRB_IUP_CONST(CENTERPARENT);
  MRB_IUP_CONST(CURRENT);
  MRB_IUP_CONST(LEFTPARENT);
  MRB_IUP_CONST(RIGHTPARENT);
  MRB_IUP_CONST(TOP);
  MRB_IUP_CONST(BOTTOM);
  MRB_IUP_CONST(TOPPARENT);
  MRB_IUP_CONST(BOTTOMPARENT);

  MRB_IUP_CONST(SHOW);
  MRB_IUP_CONST(RESTORE);
  MRB_IUP_CONST(MINIMIZE);
  MRB_IUP_CONST(MAXIMIZE);
  MRB_IUP_CONST(HIDE);

  MRB_IUP_CONST(SBUP);
  MRB_IUP_CONST(SBDN);
  MRB_IUP_CONST(SBPGUP);
  MRB_IUP_CONST(SBPGDN);
  MRB_IUP_CONST(SBPOSV);
  MRB_IUP_CONST(SBDRAGV);
  MRB_IUP_CONST(SBLEFT);
  MRB_IUP_CONST(SBRIGHT);
  MRB_IUP_CONST(SBPGLEFT);
  MRB_IUP_CONST(SBPGRIGHT);
  MRB_IUP_CONST(SBPOSH);
  MRB_IUP_CONST(SBDRAGH);

  MRB_IUP_CONST(PRIMARY);
  MRB_IUP_CONST(SECONDARY);

  MRB_IUP_CONST(RECBINARY);
  MRB_IUP_CONST(RECTEXT);

  MRB_IUP_CONST(GETPARAM_OK);
  MRB_IUP_CONST(GETPARAM_CANCEL);
  MRB_IUP_CONST(GETPARAM_HELP);

  MRB_IUP_STR(BUTTON1);
  MRB_IUP_STR(BUTTON2);
  MRB_IUP_STR(BUTTON3);
  MRB_IUP_STR(BUTTON4);
  MRB_IUP_STR(BUTTON5);

  MRB_IUP_STR(MASK_FLOAT);
  MRB_IUP_STR(MASK_UFLOAT);
  MRB_IUP_STR(MASK_EFLOAT);
  MRB_IUP_STR(MASK_UEFLOAT);
  MRB_IUP_STR(MASK_FLOATCOMMA);
  MRB_IUP_STR(MASK_UFLOATCOMMA);
  MRB_IUP_STR(MASK_INT);
  MRB_IUP_STR(MASK_UINT);
}
